name: Build

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - 'master'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '8'
          cache: 'gradle'
      - name: Run tests
        run: ./gradlew test
      - name: List Files for build
        run: ls -a build/
      - name: List Files for build/reports
        run: ls -a build/reports
      - name: List Files for build/test-results
        run: ls -a build/test-results
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
         name: Package
         path: build/libs 
