name: Build

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - 'master'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '8'
          cache: 'gradle'
      - name: Run tests
        run: ./gradlew test
      - name: List Files for build
        run: ls -a build/
      - name: List Files for build/reports
        run: ls -a build/reports/tests/test
      - name: List Files for build/test-results
        run: ls -a build/test-results/test
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
         name: Package
         path: build/test-results/test 
      - name: Build Report ALLURE
        uses: simple-elf/allure-report-action@v1.7
        if: always()
        with:
          allure_results: build/allure-results
          allure_history: allure-history
          keep_reports: 20
      - name: Upload build artifacts ALLURE
        uses: actions/upload-artifact@v4
        with:
         name: Package
         path: build/allure-results
